import { FormItem } from './struct'

const ExtensionDefault = {
  text: (id: number): FormItem => ({
    id: id,
    extension: 'text',
    name: '',
    type: 'text',
    defaultValue: '',
    unique: false,
    description: '',
    tip: '',
    require: false,
    caseEditable: false,
    rangeName: '字数',
    range: [],
    useRange: false
  }),
  number: (id: number): FormItem => ({
    id: id,
    extension: 'number',
    name: '',
    type: 'number',
    defaultValue: '0',
    unique: false,
    description: '',
    tip: '',
    require: false,
    caseEditable: false,
    rangeName: '值',
    range: [],
    useRange: false
  }),
  radio: (id: number): FormItem => ({
    id: id,
    extension: 'radio',
    name: '',
    type: 'radio',
    defaultValue: '',
    unique: false,
    description: '',
    tip: '',
    require: false,
    caseEditable: true,
    case: [],
    rangeName: '',
    range: [],
    useRange: false
  }),
  checkbox: (id: number): FormItem => ({
    id: id,
    extension: 'checkbox',
    name: '',
    type: 'checkbox',
    defaultValue: '',
    unique: false,
    description: '',
    tip: '',
    require: false,
    caseEditable: true,
    case: [],
    rangeName: '选择项数',
    range: [],
    useRange: false
  }),
  date: (id: number): FormItem => ({
    id: id,
    extension: 'date',
    name: '',
    type: 'date',
    defaultValue: '',
    unique: false,
    description: '',
    tip: '',
    require: false,
    caseEditable: false,
    rangeName: '日期',
    range: [],
    useRange: false
  }),
  textarea: (id: number): FormItem => ({
    id: id,
    extension: 'textarea',
    name: '',
    type: 'textarea',
    defaultValue: '',
    unique: false,
    description: '',
    tip: '',
    require: false,
    caseEditable: false,
    rangeName: '字数',
    range: [],
    useRange: false
  }),
  group: (id: number): FormItem => ({
    id: id,
    extension: 'group',
    name: '',
    type: '',
    defaultValue: '',
    unique: false,
    description: '',
    tip: '',
    require: false,
    caseEditable: false,
    rangeName: '',
    range: [],
    useRange: false
  }),
  //
  personName: (id: number): FormItem => ({
    id: id,
    extension: 'personName',
    name: '姓名',
    type: 'text',
    defaultValue: '',
    unique: false,
    description: '',
    tip: '请输入姓名',
    require: true,
    caseEditable: false,
    rangeName: '姓名长度',
    range: [2, 20],
    useRange: true
  }),
  teamName: (id: number): FormItem => ({
    id: id,
    extension: 'teamName',
    name: '队伍名称',
    type: 'text',
    defaultValue: '',
    unique: true,
    description: '',
    tip: '请输入队伍名称',
    require: true,
    caseEditable: false,
    rangeName: '队名长度',
    range: [1, 100],
    useRange: false
  }),
  sex: (id: number): FormItem => ({
    id: id,
    extension: 'sex',
    name: '性别',
    type: 'sex',
    defaultValue: '',
    unique: false,
    description: '',
    tip: '请选择性别',
    require: true,
    caseEditable: false,
    case: ['男', '女'],
    rangeName: '',
    range: [],
    useRange: false
  }),
  nation: (id: number): FormItem => ({
    id: id,
    extension: 'nation',
    name: '民族',
    type: 'nation',
    defaultValue: '汉族',
    unique: false,
    description: '',
    tip: '请选择民族',
    require: true,
    caseEditable: false,
    // 就不提供民族表了
    rangeName: '',
    range: [],
    useRange: false
  }),
  political: (id: number): FormItem => ({
    id: id,
    extension: 'political',
    name: '政治面貌',
    type: 'radio',
    defaultValue: '',
    unique: false,
    description: '',
    tip: '请选择政治面貌',
    require: true,
    caseEditable: true,
    case: ['群众', '团员', '预备党员', '党员'],
    rangeName: '',
    range: [],
    useRange: false
  }),
  studentNumber: (id: number): FormItem => ({
    id: id,
    extension: 'studentNumber',
    name: '学号',
    type: 'studentNumber',
    defaultValue: '',
    unique: true,
    description: '',
    tip: '请输入学号',
    require: true,
    caseEditable: false,
    rangeName: '',
    range: [],
    useRange: false
  }),
  phone: (id: number): FormItem => ({
    id: id,
    extension: 'phone',
    name: '手机号',
    type: 'phone',
    defaultValue: '',
    unique: true,
    description: '',
    tip: '请输入手机号',
    require: false,
    caseEditable: false,
    rangeName: '',
    range: [],
    useRange: false
  }),
  qq: (id: number): FormItem => ({
    id: id,
    extension: 'qq',
    name: 'QQ号',
    type: 'qq',
    defaultValue: '',
    unique: true,
    description: '',
    tip: '请输入QQ号',
    require: false,
    caseEditable: false,
    rangeName: '',
    range: [],
    useRange: false
  }),
  email: (id: number): FormItem => ({
    id: id,
    extension: 'email',
    name: '电子邮箱',
    type: 'email',
    defaultValue: '',
    unique: true,
    description: '',
    tip: '请输入邮箱',
    require: false,
    caseEditable: false,
    rangeName: '',
    range: [],
    useRange: false
  }),
  idcard: (id: number): FormItem => ({
    id: id,
    extension: 'idcard',
    name: '身份证号',
    type: 'idcard',
    defaultValue: '',
    unique: true,
    description: '',
    tip: '请输入身份证号',
    require: true,
    caseEditable: false,
    rangeName: '',
    range: [],
    useRange: false
  }),
  GPA: (id: number): FormItem => ({
    id: id,
    extension: 'GPA',
    name: 'GPA',
    type: 'GPA',
    defaultValue: '',
    unique: false,
    description: '',
    tip: '',
    require: true,
    caseEditable: false,
    rangeName: 'GPA',
    range: [0, 4],
    useRange: false
  }),
  rank: (id: number): FormItem => ({
    id: id,
    extension: 'rank',
    name: '排名',
    type: 'number',
    defaultValue: '',
    unique: false,
    description: '',
    tip: '',
    require: true,
    caseEditable: false,
    rangeName: '排名',
    range: [1, 10000],
    useRange: false
  })
}

export default ExtensionDefault
