const ExtensionDefault = {
  text: {
    idx: 2,
    extension: 'text',
    name: '',
    type: 'text',
    defaultValue: '',
    unique: false,
    description: '',
    tip: '',
    require: false,
    case: [],
    caseEditable: false,
    rangeName: '字数',
    range: [],
    useRange: false
  },
  number: {
    idx: 3,
    extension: 'number',
    name: '',
    type: 'number',
    defaultValue: '0',
    unique: false,
    description: '',
    tip: '',
    require: false,
    case: [],
    caseEditable: false,
    rangeName: '值',
    range: [],
    useRange: false
  },
  radio: {
    idx: 4,
    extension: 'radio',
    name: '',
    type: 'radio',
    defaultValue: '',
    unique: false,
    description: '',
    tip: '',
    require: false,
    caseEditable: true,
    case: [],
    rangeName: '',
    range: [],
    useRange: false
  },
  checkbox: {
    idx: 5,
    extension: 'checkbox',
    name: '',
    type: 'checkbox',
    defaultValue: '',
    unique: false,
    description: '',
    tip: '',
    require: false,
    caseEditable: true,
    case: [],
    rangeName: '选择项数',
    range: [],
    useRange: false
  },
  date: {
    idx: 6,
    extension: 'date',
    name: '',
    type: 'date',
    defaultValue: '',
    unique: false,
    description: '',
    tip: '',
    require: false,
    caseEditable: false,
    case: [],
    rangeName: '日期',
    range: [],
    useRange: false
  },
  textarea: {
    idx: 7,
    extension: 'textarea',
    name: '',
    type: 'textarea',
    defaultValue: '',
    unique: false,
    description: '',
    tip: '',
    require: false,
    caseEditable: false,
    case: [],
    rangeName: '字数',
    range: [],
    useRange: false
  },
  group: {
    idx: 8,
    extension: 'group',
    name: '',
    type: '',
    defaultValue: '',
    unique: false,
    description: '',
    tip: '',
    require: false,
    caseEditable: false,
    case: [],
    rangeName: '',
    range: [],
    useRange: false
  },
  //
  personName: {
    idx: 10,
    extension: 'personName',
    name: '姓名',
    type: 'text',
    defaultValue: '',
    unique: false,
    description: '',
    tip: '请输入姓名',
    require: true,
    caseEditable: false,
    case: [],
    rangeName: '姓名长度',
    range: [2, 20],
    useRange: true
  },
  teamName: {
    idx: 11,
    extension: 'teamName',
    name: '队伍名称',
    type: 'text',
    defaultValue: '',
    unique: true,
    description: '',
    tip: '请输入队伍名称',
    require: true,
    caseEditable: false,
    case: [],
    rangeName: '队名长度',
    range: [1, 100],
    useRange: false
  },
  sex: {
    idx: 12,
    extension: 'sex',
    name: '性别',
    type: 'sex',
    defaultValue: '',
    unique: false,
    description: '',
    tip: '请选择性别',
    require: true,
    caseEditable: false,
    case: ['男', '女'],
    rangeName: '',
    range: [],
    useRange: false
  },
  nation: {
    idx: 13,
    extension: 'nation',
    name: '民族',
    type: 'nation',
    defaultValue: '汉族',
    unique: false,
    description: '',
    tip: '请选择民族',
    require: true,
    caseEditable: false,
    case: [],
    // 就不提供民族表了
    rangeName: '',
    range: [],
    useRange: false
  },
  political: {
    idx: 14,
    extension: 'political',
    name: '政治面貌',
    type: 'radio',
    defaultValue: '',
    unique: false,
    description: '',
    tip: '请选择政治面貌',
    require: true,
    caseEditable: true,
    case: ['群众', '团员', '预备党员', '党员'],
    rangeName: '',
    range: [],
    useRange: false
  },
  studentNumber: {
    idx: 15,
    extension: 'studentNumber',
    name: '学号',
    type: 'studentNumber',
    defaultValue: '',
    unique: true,
    description: '',
    tip: '请输入学号',
    require: true,
    caseEditable: false,
    rangeName: '',
    range: [],
    useRange: false
  },
  phone: {
    idx: 16,
    extension: 'phone',
    name: '手机号',
    type: 'phone',
    defaultValue: '',
    unique: true,
    description: '',
    tip: '请输入手机号',
    require: false,
    caseEditable: false,
    rangeName: '',
    range: [],
    useRange: false
  },
  qq: {
    idx: 17,
    extension: 'qq',
    name: 'QQ号',
    type: 'qq',
    defaultValue: '',
    unique: true,
    description: '',
    tip: '请输入QQ号',
    require: false,
    caseEditable: false,
    rangeName: '',
    range: [],
    useRange: false
  },
  email: {
    idx: 18,
    extension: 'email',
    name: '电子邮箱',
    type: 'email',
    defaultValue: '',
    unique: true,
    description: '',
    tip: '请输入邮箱',
    require: false,
    caseEditable: false,
    rangeName: '',
    range: [],
    useRange: false
  },
  idcard: {
    idx: 19,
    extension: 'idcard',
    name: '身份证号',
    type: 'idcard',
    defaultValue: '',
    unique: true,
    description: '',
    tip: '请输入身份证号',
    require: true,
    caseEditable: false,
    rangeName: '',
    range: [],
    useRange: false
  },
  GPA: {
    idx: 20,
    extension: 'GPA',
    name: 'GPA',
    type: 'GPA',
    defaultValue: '',
    unique: false,
    description: '',
    tip: '',
    require: true,
    caseEditable: false,
    rangeName: 'GPA',
    range: [0, 4],
    useRange: false
  },
  rank: {
    idx: 21,
    extension: 'rank',
    name: '排名',
    type: 'number',
    defaultValue: '',
    unique: false,
    description: '',
    tip: '',
    require: true,
    caseEditable: false,
    rangeName: '排名',
    range: [1, 10000],
    useRange: false
  }
}

export default ExtensionDefault
